// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-9t-3a2SqKJdTZlW04b9Cz1kfhhON1I4',
    appId: '1:1019840858544:web:506516a8f2822ec583ae75',
    messagingSenderId: '1019840858544',
    projectId: 'notificacionespush-fdd8e',
    authDomain: 'notificacionespush-fdd8e.firebaseapp.com',
    storageBucket: 'notificacionespush-fdd8e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqs5Qffde1rw3Qs1N1jFzYtmPXZ6iNmQc',
    appId: '1:1019840858544:android:0671c71337e4f5e583ae75',
    messagingSenderId: '1019840858544',
    projectId: 'notificacionespush-fdd8e',
    storageBucket: 'notificacionespush-fdd8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw5s2UEE4Uq2OZw1xRxmlujohhcEp-AGw',
    appId: '1:1019840858544:ios:d705c5076d01434083ae75',
    messagingSenderId: '1019840858544',
    projectId: 'notificacionespush-fdd8e',
    storageBucket: 'notificacionespush-fdd8e.appspot.com',
    iosBundleId: 'com.example.notificacionespush',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw5s2UEE4Uq2OZw1xRxmlujohhcEp-AGw',
    appId: '1:1019840858544:ios:936556a1db35699a83ae75',
    messagingSenderId: '1019840858544',
    projectId: 'notificacionespush-fdd8e',
    storageBucket: 'notificacionespush-fdd8e.appspot.com',
    iosBundleId: 'com.example.notificacionespush.RunnerTests',
  );
}
