// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVdiWu_Z91ep7pMVs-Rwagm9qcJOS0m40',
    appId: '1:304928640492:web:35a4ab498bd52b183104c9',
    messagingSenderId: '304928640492',
    projectId: 'chatflutter-97da2',
    authDomain: 'chatflutter-97da2.firebaseapp.com',
    storageBucket: 'chatflutter-97da2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyZ6aSS7cTuTKuppMCDN3CepykPJKb9oM',
    appId: '1:304928640492:android:daaaa8d2631e37673104c9',
    messagingSenderId: '304928640492',
    projectId: 'chatflutter-97da2',
    storageBucket: 'chatflutter-97da2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7IGeP39OgAy4VGMtNFl5AUaRlwZfFf8I',
    appId: '1:304928640492:ios:3d83c8646b44b6343104c9',
    messagingSenderId: '304928640492',
    projectId: 'chatflutter-97da2',
    storageBucket: 'chatflutter-97da2.appspot.com',
    iosBundleId: 'com.example.chatflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7IGeP39OgAy4VGMtNFl5AUaRlwZfFf8I',
    appId: '1:304928640492:ios:8b2799a40a5c174b3104c9',
    messagingSenderId: '304928640492',
    projectId: 'chatflutter-97da2',
    storageBucket: 'chatflutter-97da2.appspot.com',
    iosBundleId: 'com.example.chatflutter.RunnerTests',
  );
}
